//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.03 at 05:13:06 PM GMT 
//


package org.opengroup.archimate31;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FontStyleEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="FontStyleEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="plain"/&gt;
 *     &lt;enumeration value="bold"/&gt;
 *     &lt;enumeration value="italic"/&gt;
 *     &lt;enumeration value="underline"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "FontStyleEnum")
@XmlEnum
public enum FontStyleEnum {

    @XmlEnumValue("plain")
    PLAIN("plain"),
    @XmlEnumValue("bold")
    BOLD("bold"),
    @XmlEnumValue("italic")
    ITALIC("italic"),
    @XmlEnumValue("underline")
    UNDERLINE("underline");
    private final String value;

    FontStyleEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FontStyleEnum fromValue(String v) {
        for (FontStyleEnum c: FontStyleEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
