//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.03 at 05:13:06 PM GMT 
//


package org.opengroup.archimate31;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.opengroup.archimate31 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Any_QNAME = new QName("http://purl.org/dc/elements/1.1/", "any");
    private final static QName _Title_QNAME = new QName("http://purl.org/dc/elements/1.1/", "title");
    private final static QName _Creator_QNAME = new QName("http://purl.org/dc/elements/1.1/", "creator");
    private final static QName _Subject_QNAME = new QName("http://purl.org/dc/elements/1.1/", "subject");
    private final static QName _Description_QNAME = new QName("http://purl.org/dc/elements/1.1/", "description");
    private final static QName _Publisher_QNAME = new QName("http://purl.org/dc/elements/1.1/", "publisher");
    private final static QName _Contributor_QNAME = new QName("http://purl.org/dc/elements/1.1/", "contributor");
    private final static QName _Date_QNAME = new QName("http://purl.org/dc/elements/1.1/", "date");
    private final static QName _Type_QNAME = new QName("http://purl.org/dc/elements/1.1/", "type");
    private final static QName _Format_QNAME = new QName("http://purl.org/dc/elements/1.1/", "format");
    private final static QName _Identifier_QNAME = new QName("http://purl.org/dc/elements/1.1/", "identifier");
    private final static QName _Source_QNAME = new QName("http://purl.org/dc/elements/1.1/", "source");
    private final static QName _Language_QNAME = new QName("http://purl.org/dc/elements/1.1/", "language");
    private final static QName _Relation_QNAME = new QName("http://purl.org/dc/elements/1.1/", "relation");
    private final static QName _Coverage_QNAME = new QName("http://purl.org/dc/elements/1.1/", "coverage");
    private final static QName _Rights_QNAME = new QName("http://purl.org/dc/elements/1.1/", "rights");
    private final static QName _Model_QNAME = new QName("http://www.opengroup.org/xsd/archimate/3.0/", "model");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.opengroup.archimate31
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SimpleLiteral }
     * 
     */
    public SimpleLiteral createSimpleLiteral() {
        return new SimpleLiteral();
    }

    /**
     * Create an instance of {@link ElementContainer }
     * 
     */
    public ElementContainer createElementContainer() {
        return new ElementContainer();
    }

    /**
     * Create an instance of {@link ModelType }
     * 
     */
    public ModelType createModelType() {
        return new ModelType();
    }

    /**
     * Create an instance of {@link LangStringType }
     * 
     */
    public LangStringType createLangStringType() {
        return new LangStringType();
    }

    /**
     * Create an instance of {@link PreservedLangStringType }
     * 
     */
    public PreservedLangStringType createPreservedLangStringType() {
        return new PreservedLangStringType();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link MetadataType }
     * 
     */
    public MetadataType createMetadataType() {
        return new MetadataType();
    }

    /**
     * Create an instance of {@link SchemaInfoType }
     * 
     */
    public SchemaInfoType createSchemaInfoType() {
        return new SchemaInfoType();
    }

    /**
     * Create an instance of {@link PropertyDefinitionsType }
     * 
     */
    public PropertyDefinitionsType createPropertyDefinitionsType() {
        return new PropertyDefinitionsType();
    }

    /**
     * Create an instance of {@link PropertyDefinitionType }
     * 
     */
    public PropertyDefinitionType createPropertyDefinitionType() {
        return new PropertyDefinitionType();
    }

    /**
     * Create an instance of {@link PropertiesType }
     * 
     */
    public PropertiesType createPropertiesType() {
        return new PropertiesType();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link ElementsType }
     * 
     */
    public ElementsType createElementsType() {
        return new ElementsType();
    }

    /**
     * Create an instance of {@link RelationshipsType }
     * 
     */
    public RelationshipsType createRelationshipsType() {
        return new RelationshipsType();
    }

    /**
     * Create an instance of {@link OrganizationsType }
     * 
     */
    public OrganizationsType createOrganizationsType() {
        return new OrganizationsType();
    }

    /**
     * Create an instance of {@link OrganizationType }
     * 
     */
    public OrganizationType createOrganizationType() {
        return new OrganizationType();
    }

    /**
     * Create an instance of {@link BusinessActor }
     * 
     */
    public BusinessActor createBusinessActor() {
        return new BusinessActor();
    }

    /**
     * Create an instance of {@link BusinessRole }
     * 
     */
    public BusinessRole createBusinessRole() {
        return new BusinessRole();
    }

    /**
     * Create an instance of {@link BusinessCollaboration }
     * 
     */
    public BusinessCollaboration createBusinessCollaboration() {
        return new BusinessCollaboration();
    }

    /**
     * Create an instance of {@link BusinessInterface }
     * 
     */
    public BusinessInterface createBusinessInterface() {
        return new BusinessInterface();
    }

    /**
     * Create an instance of {@link BusinessProcess }
     * 
     */
    public BusinessProcess createBusinessProcess() {
        return new BusinessProcess();
    }

    /**
     * Create an instance of {@link BusinessFunction }
     * 
     */
    public BusinessFunction createBusinessFunction() {
        return new BusinessFunction();
    }

    /**
     * Create an instance of {@link BusinessInteraction }
     * 
     */
    public BusinessInteraction createBusinessInteraction() {
        return new BusinessInteraction();
    }

    /**
     * Create an instance of {@link BusinessEvent }
     * 
     */
    public BusinessEvent createBusinessEvent() {
        return new BusinessEvent();
    }

    /**
     * Create an instance of {@link BusinessService }
     * 
     */
    public BusinessService createBusinessService() {
        return new BusinessService();
    }

    /**
     * Create an instance of {@link BusinessObject }
     * 
     */
    public BusinessObject createBusinessObject() {
        return new BusinessObject();
    }

    /**
     * Create an instance of {@link Contract }
     * 
     */
    public Contract createContract() {
        return new Contract();
    }

    /**
     * Create an instance of {@link Representation }
     * 
     */
    public Representation createRepresentation() {
        return new Representation();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link ApplicationComponent }
     * 
     */
    public ApplicationComponent createApplicationComponent() {
        return new ApplicationComponent();
    }

    /**
     * Create an instance of {@link ApplicationCollaboration }
     * 
     */
    public ApplicationCollaboration createApplicationCollaboration() {
        return new ApplicationCollaboration();
    }

    /**
     * Create an instance of {@link ApplicationInterface }
     * 
     */
    public ApplicationInterface createApplicationInterface() {
        return new ApplicationInterface();
    }

    /**
     * Create an instance of {@link ApplicationFunction }
     * 
     */
    public ApplicationFunction createApplicationFunction() {
        return new ApplicationFunction();
    }

    /**
     * Create an instance of {@link ApplicationInteraction }
     * 
     */
    public ApplicationInteraction createApplicationInteraction() {
        return new ApplicationInteraction();
    }

    /**
     * Create an instance of {@link ApplicationProcess }
     * 
     */
    public ApplicationProcess createApplicationProcess() {
        return new ApplicationProcess();
    }

    /**
     * Create an instance of {@link ApplicationEvent }
     * 
     */
    public ApplicationEvent createApplicationEvent() {
        return new ApplicationEvent();
    }

    /**
     * Create an instance of {@link ApplicationService }
     * 
     */
    public ApplicationService createApplicationService() {
        return new ApplicationService();
    }

    /**
     * Create an instance of {@link DataObject }
     * 
     */
    public DataObject createDataObject() {
        return new DataObject();
    }

    /**
     * Create an instance of {@link Node }
     * 
     */
    public Node createNode() {
        return new Node();
    }

    /**
     * Create an instance of {@link Device }
     * 
     */
    public Device createDevice() {
        return new Device();
    }

    /**
     * Create an instance of {@link SystemSoftware }
     * 
     */
    public SystemSoftware createSystemSoftware() {
        return new SystemSoftware();
    }

    /**
     * Create an instance of {@link TechnologyCollaboration }
     * 
     */
    public TechnologyCollaboration createTechnologyCollaboration() {
        return new TechnologyCollaboration();
    }

    /**
     * Create an instance of {@link TechnologyInterface }
     * 
     */
    public TechnologyInterface createTechnologyInterface() {
        return new TechnologyInterface();
    }

    /**
     * Create an instance of {@link Path }
     * 
     */
    public Path createPath() {
        return new Path();
    }

    /**
     * Create an instance of {@link CommunicationNetwork }
     * 
     */
    public CommunicationNetwork createCommunicationNetwork() {
        return new CommunicationNetwork();
    }

    /**
     * Create an instance of {@link TechnologyFunction }
     * 
     */
    public TechnologyFunction createTechnologyFunction() {
        return new TechnologyFunction();
    }

    /**
     * Create an instance of {@link TechnologyProcess }
     * 
     */
    public TechnologyProcess createTechnologyProcess() {
        return new TechnologyProcess();
    }

    /**
     * Create an instance of {@link TechnologyInteraction }
     * 
     */
    public TechnologyInteraction createTechnologyInteraction() {
        return new TechnologyInteraction();
    }

    /**
     * Create an instance of {@link TechnologyEvent }
     * 
     */
    public TechnologyEvent createTechnologyEvent() {
        return new TechnologyEvent();
    }

    /**
     * Create an instance of {@link TechnologyService }
     * 
     */
    public TechnologyService createTechnologyService() {
        return new TechnologyService();
    }

    /**
     * Create an instance of {@link Artifact }
     * 
     */
    public Artifact createArtifact() {
        return new Artifact();
    }

    /**
     * Create an instance of {@link Equipment }
     * 
     */
    public Equipment createEquipment() {
        return new Equipment();
    }

    /**
     * Create an instance of {@link Facility }
     * 
     */
    public Facility createFacility() {
        return new Facility();
    }

    /**
     * Create an instance of {@link DistributionNetwork }
     * 
     */
    public DistributionNetwork createDistributionNetwork() {
        return new DistributionNetwork();
    }

    /**
     * Create an instance of {@link Material }
     * 
     */
    public Material createMaterial() {
        return new Material();
    }

    /**
     * Create an instance of {@link Stakeholder }
     * 
     */
    public Stakeholder createStakeholder() {
        return new Stakeholder();
    }

    /**
     * Create an instance of {@link Driver }
     * 
     */
    public Driver createDriver() {
        return new Driver();
    }

    /**
     * Create an instance of {@link Assessment }
     * 
     */
    public Assessment createAssessment() {
        return new Assessment();
    }

    /**
     * Create an instance of {@link Goal }
     * 
     */
    public Goal createGoal() {
        return new Goal();
    }

    /**
     * Create an instance of {@link Outcome }
     * 
     */
    public Outcome createOutcome() {
        return new Outcome();
    }

    /**
     * Create an instance of {@link Principle }
     * 
     */
    public Principle createPrinciple() {
        return new Principle();
    }

    /**
     * Create an instance of {@link Requirement }
     * 
     */
    public Requirement createRequirement() {
        return new Requirement();
    }

    /**
     * Create an instance of {@link Constraint }
     * 
     */
    public Constraint createConstraint() {
        return new Constraint();
    }

    /**
     * Create an instance of {@link Meaning }
     * 
     */
    public Meaning createMeaning() {
        return new Meaning();
    }

    /**
     * Create an instance of {@link Value }
     * 
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link Capability }
     * 
     */
    public Capability createCapability() {
        return new Capability();
    }

    /**
     * Create an instance of {@link CourseOfAction }
     * 
     */
    public CourseOfAction createCourseOfAction() {
        return new CourseOfAction();
    }

    /**
     * Create an instance of {@link ValueStream }
     * 
     */
    public ValueStream createValueStream() {
        return new ValueStream();
    }

    /**
     * Create an instance of {@link WorkPackage }
     * 
     */
    public WorkPackage createWorkPackage() {
        return new WorkPackage();
    }

    /**
     * Create an instance of {@link Deliverable }
     * 
     */
    public Deliverable createDeliverable() {
        return new Deliverable();
    }

    /**
     * Create an instance of {@link ImplementationEvent }
     * 
     */
    public ImplementationEvent createImplementationEvent() {
        return new ImplementationEvent();
    }

    /**
     * Create an instance of {@link Plateau }
     * 
     */
    public Plateau createPlateau() {
        return new Plateau();
    }

    /**
     * Create an instance of {@link Gap }
     * 
     */
    public Gap createGap() {
        return new Gap();
    }

    /**
     * Create an instance of {@link Grouping }
     * 
     */
    public Grouping createGrouping() {
        return new Grouping();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link AndJunction }
     * 
     */
    public AndJunction createAndJunction() {
        return new AndJunction();
    }

    /**
     * Create an instance of {@link OrJunction }
     * 
     */
    public OrJunction createOrJunction() {
        return new OrJunction();
    }

    /**
     * Create an instance of {@link Composition }
     * 
     */
    public Composition createComposition() {
        return new Composition();
    }

    /**
     * Create an instance of {@link Aggregation }
     * 
     */
    public Aggregation createAggregation() {
        return new Aggregation();
    }

    /**
     * Create an instance of {@link Assignment }
     * 
     */
    public Assignment createAssignment() {
        return new Assignment();
    }

    /**
     * Create an instance of {@link Realization }
     * 
     */
    public Realization createRealization() {
        return new Realization();
    }

    /**
     * Create an instance of {@link Serving }
     * 
     */
    public Serving createServing() {
        return new Serving();
    }

    /**
     * Create an instance of {@link Access }
     * 
     */
    public Access createAccess() {
        return new Access();
    }

    /**
     * Create an instance of {@link Influence }
     * 
     */
    public Influence createInfluence() {
        return new Influence();
    }

    /**
     * Create an instance of {@link Triggering }
     * 
     */
    public Triggering createTriggering() {
        return new Triggering();
    }

    /**
     * Create an instance of {@link Flow }
     * 
     */
    public Flow createFlow() {
        return new Flow();
    }

    /**
     * Create an instance of {@link Specialization }
     * 
     */
    public Specialization createSpecialization() {
        return new Specialization();
    }

    /**
     * Create an instance of {@link Association }
     * 
     */
    public Association createAssociation() {
        return new Association();
    }

    /**
     * Create an instance of {@link ViewsType }
     * 
     */
    public ViewsType createViewsType() {
        return new ViewsType();
    }

    /**
     * Create an instance of {@link ViewpointsType }
     * 
     */
    public ViewpointsType createViewpointsType() {
        return new ViewpointsType();
    }

    /**
     * Create an instance of {@link ViewpointType }
     * 
     */
    public ViewpointType createViewpointType() {
        return new ViewpointType();
    }

    /**
     * Create an instance of {@link ModelingNoteType }
     * 
     */
    public ModelingNoteType createModelingNoteType() {
        return new ModelingNoteType();
    }

    /**
     * Create an instance of {@link ConcernType }
     * 
     */
    public ConcernType createConcernType() {
        return new ConcernType();
    }

    /**
     * Create an instance of {@link StakeholdersType }
     * 
     */
    public StakeholdersType createStakeholdersType() {
        return new StakeholdersType();
    }

    /**
     * Create an instance of {@link StakeholderType }
     * 
     */
    public StakeholderType createStakeholderType() {
        return new StakeholderType();
    }

    /**
     * Create an instance of {@link AllowedElementTypeType }
     * 
     */
    public AllowedElementTypeType createAllowedElementTypeType() {
        return new AllowedElementTypeType();
    }

    /**
     * Create an instance of {@link AllowedRelationshipTypeType }
     * 
     */
    public AllowedRelationshipTypeType createAllowedRelationshipTypeType() {
        return new AllowedRelationshipTypeType();
    }

    /**
     * Create an instance of {@link DiagramsType }
     * 
     */
    public DiagramsType createDiagramsType() {
        return new DiagramsType();
    }

    /**
     * Create an instance of {@link Diagram }
     * 
     */
    public Diagram createDiagram() {
        return new Diagram();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link Label }
     * 
     */
    public Label createLabel() {
        return new Label();
    }

    /**
     * Create an instance of {@link Container }
     * 
     */
    public Container createContainer() {
        return new Container();
    }

    /**
     * Create an instance of {@link Element }
     * 
     */
    public Element createElement() {
        return new Element();
    }

    /**
     * Create an instance of {@link Line }
     * 
     */
    public Line createLine() {
        return new Line();
    }

    /**
     * Create an instance of {@link Relationship }
     * 
     */
    public Relationship createRelationship() {
        return new Relationship();
    }

    /**
     * Create an instance of {@link NestingRelationship }
     * 
     */
    public NestingRelationship createNestingRelationship() {
        return new NestingRelationship();
    }

    /**
     * Create an instance of {@link StyleType }
     * 
     */
    public StyleType createStyleType() {
        return new StyleType();
    }

    /**
     * Create an instance of {@link RGBColorType }
     * 
     */
    public RGBColorType createRGBColorType() {
        return new RGBColorType();
    }

    /**
     * Create an instance of {@link FontType }
     * 
     */
    public FontType createFontType() {
        return new FontType();
    }

    /**
     * Create an instance of {@link OriginalViewsType }
     * 
     */
    public OriginalViewsType createOriginalViewsType() {
        return new OriginalViewsType();
    }

    /**
     * Create an instance of {@link OriginalModelType }
     * 
     */
    public OriginalModelType createOriginalModelType() {
        return new OriginalModelType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "any")
    public JAXBElement<SimpleLiteral> createAny(SimpleLiteral value) {
        return new JAXBElement<SimpleLiteral>(_Any_QNAME, SimpleLiteral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "title", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "any")
    public JAXBElement<SimpleLiteral> createTitle(SimpleLiteral value) {
        return new JAXBElement<SimpleLiteral>(_Title_QNAME, SimpleLiteral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "creator", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "any")
    public JAXBElement<SimpleLiteral> createCreator(SimpleLiteral value) {
        return new JAXBElement<SimpleLiteral>(_Creator_QNAME, SimpleLiteral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "subject", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "any")
    public JAXBElement<SimpleLiteral> createSubject(SimpleLiteral value) {
        return new JAXBElement<SimpleLiteral>(_Subject_QNAME, SimpleLiteral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "description", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "any")
    public JAXBElement<SimpleLiteral> createDescription(SimpleLiteral value) {
        return new JAXBElement<SimpleLiteral>(_Description_QNAME, SimpleLiteral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "publisher", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "any")
    public JAXBElement<SimpleLiteral> createPublisher(SimpleLiteral value) {
        return new JAXBElement<SimpleLiteral>(_Publisher_QNAME, SimpleLiteral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "contributor", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "any")
    public JAXBElement<SimpleLiteral> createContributor(SimpleLiteral value) {
        return new JAXBElement<SimpleLiteral>(_Contributor_QNAME, SimpleLiteral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "date", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "any")
    public JAXBElement<SimpleLiteral> createDate(SimpleLiteral value) {
        return new JAXBElement<SimpleLiteral>(_Date_QNAME, SimpleLiteral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "type", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "any")
    public JAXBElement<SimpleLiteral> createType(SimpleLiteral value) {
        return new JAXBElement<SimpleLiteral>(_Type_QNAME, SimpleLiteral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "format", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "any")
    public JAXBElement<SimpleLiteral> createFormat(SimpleLiteral value) {
        return new JAXBElement<SimpleLiteral>(_Format_QNAME, SimpleLiteral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "identifier", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "any")
    public JAXBElement<SimpleLiteral> createIdentifier(SimpleLiteral value) {
        return new JAXBElement<SimpleLiteral>(_Identifier_QNAME, SimpleLiteral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "source", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "any")
    public JAXBElement<SimpleLiteral> createSource(SimpleLiteral value) {
        return new JAXBElement<SimpleLiteral>(_Source_QNAME, SimpleLiteral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "language", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "any")
    public JAXBElement<SimpleLiteral> createLanguage(SimpleLiteral value) {
        return new JAXBElement<SimpleLiteral>(_Language_QNAME, SimpleLiteral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "relation", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "any")
    public JAXBElement<SimpleLiteral> createRelation(SimpleLiteral value) {
        return new JAXBElement<SimpleLiteral>(_Relation_QNAME, SimpleLiteral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "coverage", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "any")
    public JAXBElement<SimpleLiteral> createCoverage(SimpleLiteral value) {
        return new JAXBElement<SimpleLiteral>(_Coverage_QNAME, SimpleLiteral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SimpleLiteral }{@code >}
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "rights", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "any")
    public JAXBElement<SimpleLiteral> createRights(SimpleLiteral value) {
        return new JAXBElement<SimpleLiteral>(_Rights_QNAME, SimpleLiteral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModelType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ModelType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opengroup.org/xsd/archimate/3.0/", name = "model")
    public JAXBElement<ModelType> createModel(ModelType value) {
        return new JAXBElement<ModelType>(_Model_QNAME, ModelType.class, null, value);
    }

}
