//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.19 at 02:03:38 PM GMT 
//


package org.opengroup.archimate31;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 *                 This is a container for all of the Views in the model.
 *             
 * 
 * <p>Java class for ViewsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ViewsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="viewpoints" type="{http://www.opengroup.org/xsd/archimate/3.0/}ViewpointsType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "viewpoints"
})
@XmlSeeAlso({
    ViewsType.class
})
public class OriginalViewsType {

    protected ViewpointsType viewpoints;

    /**
     * Gets the value of the viewpoints property.
     * 
     * @return
     *     possible object is
     *     {@link ViewpointsType }
     *     
     */
    public ViewpointsType getViewpoints() {
        return viewpoints;
    }

    /**
     * Sets the value of the viewpoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewpointsType }
     *     
     */
    public void setViewpoints(ViewpointsType value) {
        this.viewpoints = value;
    }

}
