//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.19 at 02:03:38 PM GMT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.opengroup.org/xsd/archimate/3.0/", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.opengroup.archimate31;
