//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.18 at 10:03:29 PM GMT 
//


package org.archimate31;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Access complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Access"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opengroup.org/xsd/archimate/3.0/}RelationshipType"&gt;
 *       &lt;attribute name="accessType" type="{http://www.opengroup.org/xsd/archimate/3.0/}AccessTypeEnum" default="Access" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Access")
public class Access
    extends RelationshipType
{

    @XmlAttribute(name = "accessType")
    protected AccessTypeEnum accessType;

    /**
     * Gets the value of the accessType property.
     * 
     * @return
     *     possible object is
     *     {@link AccessTypeEnum }
     *     
     */
    public AccessTypeEnum getAccessType() {
        if (accessType == null) {
            return AccessTypeEnum.ACCESS;
        } else {
            return accessType;
        }
    }

    /**
     * Sets the value of the accessType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessTypeEnum }
     *     
     */
    public void setAccessType(AccessTypeEnum value) {
        this.accessType = value;
    }

}
