//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.18 at 10:03:29 PM GMT 
//


package org.archimate31;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 *                 Node type to allow a Label in a Artifact. the "label" element holds the info for the Note.
 *             
 * 
 * <p>Java class for Label complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Label"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opengroup.org/xsd/archimate/3.0/}ViewNodeType"&gt;
 *       &lt;attribute name="conceptRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *       &lt;attribute name="xpathPart" type="{http://www.opengroup.org/xsd/archimate/3.0/}XPATH_2.0_Expression" /&gt;
 *       &lt;anyAttribute namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Label")
public class Label
    extends ViewNodeType
{

    @XmlAttribute(name = "conceptRef")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object conceptRef;
    @XmlAttribute(name = "xpathPart")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String xpathPart;

    /**
     * Gets the value of the conceptRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getConceptRef() {
        return conceptRef;
    }

    /**
     * Sets the value of the conceptRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setConceptRef(Object value) {
        this.conceptRef = value;
    }

    /**
     * Gets the value of the xpathPart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXpathPart() {
        return xpathPart;
    }

    /**
     * Sets the value of the xpathPart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXpathPart(String value) {
        this.xpathPart = value;
    }

}
