//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.18 at 10:03:29 PM GMT 
//


package org.archimate31;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 *                 RGB Color type.
 *                 The r, g, b attributes range from 0 - 255.
 *                 The a (alpha) transparency attribute is optional. 0 = full transparency, 100 = opaque.
 *             
 * 
 * <p>Java class for RGBColorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RGBColorType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="r" use="required" type="{http://www.opengroup.org/xsd/archimate/3.0/}RGBValueType" /&gt;
 *       &lt;attribute name="g" use="required" type="{http://www.opengroup.org/xsd/archimate/3.0/}RGBValueType" /&gt;
 *       &lt;attribute name="b" use="required" type="{http://www.opengroup.org/xsd/archimate/3.0/}RGBValueType" /&gt;
 *       &lt;attribute name="a"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte"&gt;
 *             &lt;minInclusive value="0"/&gt;
 *             &lt;maxInclusive value="100"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RGBColorType")
public class RGBColorType {

    @XmlAttribute(name = "r", required = true)
    protected short r;
    @XmlAttribute(name = "g", required = true)
    protected short g;
    @XmlAttribute(name = "b", required = true)
    protected short b;
    @XmlAttribute(name = "a")
    protected Short a;

    /**
     * Gets the value of the r property.
     * 
     */
    public short getR() {
        return r;
    }

    /**
     * Sets the value of the r property.
     * 
     */
    public void setR(short value) {
        this.r = value;
    }

    /**
     * Gets the value of the g property.
     * 
     */
    public short getG() {
        return g;
    }

    /**
     * Sets the value of the g property.
     * 
     */
    public void setG(short value) {
        this.g = value;
    }

    /**
     * Gets the value of the b property.
     * 
     */
    public short getB() {
        return b;
    }

    /**
     * Sets the value of the b property.
     * 
     */
    public void setB(short value) {
        this.b = value;
    }

    /**
     * Gets the value of the a property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getA() {
        return a;
    }

    /**
     * Sets the value of the a property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setA(Short value) {
        this.a = value;
    }

}
